if: (branch = development) OR (branch = master) OR (type = pull_request) OR (tag IS present)
dist: xenial
language: node_js
node_js:
  - 'node'
matrix:
  include:
    - env:
        - REACT_APP_NETWORK='mainnet'
        - INFURA_API_KEY=${INFURA_API_KEY}
      if: (branch = master AND NOT type = pull_request) OR tag IS present
    - env:
        - REACT_APP_NETWORK='rinkeby'
        - INFURA_API_KEY=${INFURA_API_KEY}
      if: (branch != master) OR tag IS NOT present
cache:
  yarn: true
before_install:
  - yarn install
  # Needed to deploy pull request and releases
  - pip install awscli --upgrade --user
before_script:
- yarn build
script:
  - echo "Skip tests" # no test cases for the project
deploy:
  # Development environment
  - provider: s3
    bucket: $DEV_BUCKET_NAME
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    local_dir: build
    upload-dir: app
    region: $AWS_DEFAULT_REGION
    on:
      branch: development

    # Staging environment
  - provider: s3
    bucket: $STAGING_BUCKET_NAME
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    local_dir: build
    upload-dir: current/app
    region: $AWS_DEFAULT_REGION
    on:
      branch: master

    # Prepare production deployment
  - provider: s3
    bucket: $STAGING_BUCKET_NAME
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    access_key_id: $AWS_ACCESS_KEY_ID
    local_dir: build
    upload-dir: releases/$TRAVIS_TAG
    region: $AWS_DEFAULT_REGION
    on:
      tags: true
  - provider: script
    script: ./config/travis/prepare_production_deployment.sh
    on:
      tags: true
